services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.dockerfile
    volumes:
      - type: bind
        source: ./backend/app
        target: /rails/app
    ports:
      - "3000:3000"
    
  frontend:
    build: ./frontend
    ports: 
      - "8080:8080"
    volumes:
      - type: bind
        source: ./frontend/
        target: /frontend
      - /frontend/node_modules