services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.dockerfile
    volumes:
      - type: bind
        source: ./backend/app
        target: /rails/app
    ports:
      - "3000:3000"
    
  frontend:
    build: ./frontend
    ports: 
      - "8080:8080"
    volumes:
      - type: bind
        source: ./frontend/src
        target: /frontend/src
      - type: bind
        source: ./frontend/src/components
        target: /frontend/src/components
      - type: bind
        source: ./frontend/src/views
        target: /frontend/src/views
      - type: bind
        source: ./frontend/src/router
        target: /frontend/src/router
      - /frontend/node_modules